# Install pre-commit hooks via
# pre-commit install

exclude: >
    (?x)^(
      \.vscode/settings\.json|
      tests/test_tocdirective/.*
    )$

repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black

  # - repo: https://github.com/asottile/blacken-docs
  #   rev: v1.7.0
  #   hooks:
  #    - id: blacken-docs
  #   - additional_dependencies: [black]
