name: notebook
channels:
  - eoas_ubc
  - conda-forge
dependencies:
  - base-notebook=2020.09.05
  # NOTE: pip required for running tests in this repo
  - pip=20
  - numpy
  - scipy
  - matplotlib
  - Pillow
  - jupytext
# conda-lock -f environment.yml -p linux-64
