name: notebook
channels:
  - eoas_ubc
  - conda-forge
dependencies:
  - python=3.7
  - base-notebook=2020.08.24
  # NOTE: pip required for running tests in this repo
  - pip=20
  - numpy=1.19
  - scipy=1.5
  - matplotlib=3.3
  - Pillow=7.2
  - requests=2.24
  - SimPEG>=0.14.2
  - empymod>=2.0.0
  - cvxopt=1.2
