version: '3.8'

services:
  jupyterhub_test29:
    build: hub_image
    image: phaustin/hub07:sep29
    container_name: jupyterhub_sep29
    depends_on: [notebook29]
    ports:
      - ${NB_PORT}:8000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net_test29

  notebook29:
    image: phaustin/notebook:sep29
    build:
      context: notebook_image
    container_name: notebook_sep29

# force the network name to be "jupyterhub"
# this needs to be matched in jupyterhub_config.py by:
# c.DockerSpawner.network_name = 'jupyterhub'
networks:
    net_test29:
      driver: bridge
      name: net_sep29

