version: '3.8'

services:
  jupyterhub_test:
    build: hub_image
    image: phaustin/hub07:text_sep28
    depends_on: [notebook]
    ports:
      - ${NB_PORT}:8000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net_test

  notebook:
    image: phaustin/notebook:text_sep28
    build:
      context: notebook_image

# force the network name to be "jupyterhub"
# this needs to be matched in jupyterhub_config.py by:
# c.DockerSpawner.network_name = 'jupyterhub'
networks:
    net_test:
      driver: bridge

